services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
      args:
        UID: ${UID:-20000}
        GID: ${GID:-20000}
    command: sleep infinity
    env_file: devcontainer.env
    volumes:
      - ..:/home/ossans_navi/app
